name: miaudota_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  intl: ^0.16.0
  flushbar: ^1.9.1
  flutter_bloc: ^2.0.0
  meta: ^1.1.6
  equatable: ^0.6.0
  http: ^0.12.0+2
  flutter_secure_storage: ^3.3.1+1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
