name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image:  cirrusci/flutter:latest
    
    steps:
    - uses: actions/checkout@v1
    # - name: Analyze code
    #   run: flutter analyze
    - name: Run tests
      run: |
        cd miaudota_app
        flutter test --merge-coverage test/
