name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image:  cirrusci/flutter
    
    steps:
    - uses: actions/checkout@v1
    - name: Enter in the directory of app
      run: cd miaudota_app/
    - name: Analyze lib code
      run: sudo flutter analyze
    - name: Run tests
      run: sudo flutter run test --merge-coverage test/
