name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image:  cirrusci/flutter:latest
    
    steps:
    - uses: actions/checkout@v1
    # - name: Analyze code
    #   run: flutter analyze
    - name: List files
      run: ls -la
    - name: Run tests
      run: flutter test --merge-coverage miaudota_app/test/
