name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image:  cirrusci/flutter:latest
    
    steps:
    - uses: actions/checkout@v1
    # - name: Analyze code
    #   run: flutter analyze
    - name: cd
      run: cd miaudota_app
    - name: ls
      run: ls
    - name: Run tests
      run: flutter test --merge-coverage
